# name: Rank Pipeline

# # on:
# #   schedule:
# #     - cron: '*/5 * * * *' # Runs the job every 5 minutes

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2
      
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.11' # Use the appropriate Python version
        
#     - name: Install dependencies
#       run: |
#         pip install -r rank-pipeline/requirements.txt
#         # You might need to adjust this according to your project setup
        
#     - name: Run Python script
#       run: python rank-pipeline/extraction.py

#     - name: Commit and push CSV files
#       run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git add .
#         git commit -m "Update CSV files"
#         git push
